version: "3.9"

services:
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - 5431:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10S
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

  web:
    build: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

volumes:
  - pgdata:
